name: 'Zephyr CI Setup'
description: 'Set up Zephyr environment for Zephyr CI'
inputs:
  workspace_directory:
    description: "Path to Zephyr workspace"
    required: true
    type: string
  stage: 
    description: "Stage of the CI process"
    required: false
    default: "all"
    type: string
runs:
  using: "composite"
  steps:
    - name: "Install CI tooling"
      run: |
        echo "$GITHUB_ACTION_PATH"
        CI_TOOLS_PATH="$(cd $(dirname "$GITHUB_ACTION_PATH")/../../ci && pwd)"
        echo "CI Tools Path: $CI_TOOLS_PATH"
        pip3 install "${CI_TOOLS_PATH}"
      shell: bash
    - name: "Zephyr Setup"
      if: ${{ inputs.stage == 'all' || inputs.stage == 'build' }}
      run: |
          cd ${{ inputs.workspace_directory }}
          west update
          west sdk install
      shell: bash
    - name: "Set Flashing Tools"
      run: |
          sudo apt-get install libusb-dev || true
          git clone https://github.com/PaulStoffregen/teensy_loader_cli
          cd teensy_loader_cli
          make
          echo PATH="$(pwd):$PATH" >> $GITHUB_ENV
      shell: bash
