add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/default/zephyr-config")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-zephyr/Drv/LoRa")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-zephyr/Os")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-zephyr/Drv/ZephyrUartDriver")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-zephyr/Drv/ZephyrGpioDriver")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-zephyr/Drv/ZephyrRateDriver")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-zephyr/Drv/ZephyrI2cDriver")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-zephyr/Drv/ZephyrSpiDriver")
